### ISSUE TITLE
How to run multiple images at same time and fork to different local ports

### ISSUE THREAD

**Issue by wangzhe3224** [ryankennedyio/ib-docker#10]
I try to run multiple ib images at the same machine at the same time to manege different account. So I guess I have to run images withe different ports open? e.g. ib1: 4003, ib2:4004 ..

How can I revise the config file? Now I change them to:

  ports:
    - "4005:4005"
    - "5905:5905"

The docker part works fine. Although the last line of the terminal is still:

`tws_1  | Forking :::4001 onto 0.0.0.0:4003\n`

Forking 4001 to 4003... I suppose it should be forked to 4005?

Then I tried to connect the port 4005, the api give me back following error:

`Exception caught while reading socket - Connection reset by peer.`

If I leave the port info as it is (4003, 5900), no problem.

Could someone please give me a clue how to handle this situation? 
OR
is there any other way to handle multi accounts at IB?

Thanks a lot!
Zhe

**Comment by chrism2671** [comment]
I think it should be:

```
4000:4003
external:internal
```

**Comment by wangzhe3224** [comment]
@chrism2671 
Thanks a lot. I will give it a try

**Comment by wangzhe3224** [comment]
@chrism2671 That works.
