### ISSUE TITLE
tws_1 | xvfb-run: error: Xvfb failed to start

### ISSUE THREAD

**Issue by alexblickenstaff** [ryankennedyio/ib-docker#3]
I'm getting this error

`tws_1 | xvfb-run: error: Xvfb failed to start`

when I run the script via a crontab. When I run it normally (manually), there are no problems. Do you know if there's anything regarding xvfb that could break when running via a crontab?

**Comment by alexblickenstaff** [comment]
Not sure if running via crontab was indeed the culprit, but changing from

```
xvfb-run /opt/IBController/Scripts/DisplayBannerAndLaunch.sh &
to
xvfb-run -a /opt/IBController/Scripts/DisplayBannerAndLaunch.sh &
```

(adding `-a`) seems to have resolved the issue

**Comment by ryankennedyio** [comment]
Yeah this one seems to happen intermittently -- I often can't reproduce. Has this solved it every time, say over 5 or 10 attempts?

**Comment by alexblickenstaff** [comment]
So far yes. I haven't run tons of times in a row, but I'm pretty sure it's helping. It hasn't happened again since I added the `-a`.

**Comment by ryankennedyio** [comment]
Closed since removing xvfb-run: https://github.com/ryankennedyio/ib-docker/commit/cd502ed1b2cce8c865b0d75b81ab973068e36cab
